export interface SignaturePlacement {
  left: number
  top: number
  width: number
  height: number
  page: number
}

export interface PdfManifestEntry {
  key: string
  signed?: boolean
  name: string
  fileName: string
  pageSizeCm: string
  orientation: 'portrait' | 'landscape'
  userUnit: number
  signaturePlacement: SignaturePlacement[]
}

export const PDF_MANIFEST: PdfManifestEntry[] = [
  {
    key: 'suite-00',
    signed: false,
    name: 'Standard A4 portrait (v2, UU=1)',
    fileName: 'pdf_suite_00.pdf',
    pageSizeCm: '21.00 x 29.70',
    orientation: 'portrait',
    userUnit: 1.0,
    signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  },
  {
    key: 'suite-01',
    signed: false,
    name: 'A4, portrait, UU=1',
    fileName: 'pdf_suite_01.pdf',
    pageSizeCm: '21.00 x 29.70',
    orientation: 'portrait',
    userUnit: 1.0,
    signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  },
  // {
  //   key: 'suite-02',
  //   signed: false,
  //   name: 'A4, landscape, UU=1',
  //   fileName: 'pdf_suite_02.pdf',
  //   pageSizeCm: '29.70 x 21.00',
  //   orientation: 'landscape',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-03',
  //   signed: false,
  //   name: 'Letter, portrait, UU=1',
  //   fileName: 'pdf_suite_03.pdf',
  //   pageSizeCm: '21.59 x 27.94',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-04',
  //   signed: false,
  //   name: 'Letter, landscape, UU=1',
  //   fileName: 'pdf_suite_04.pdf',
  //   pageSizeCm: '27.94 x 21.59',
  //   orientation: 'landscape',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-05',
  //   signed: false,
  //   name: 'Legal, portrait, UU=1',
  //   fileName: 'pdf_suite_05.pdf',
  //   pageSizeCm: '21.59 x 35.56',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-06',
  //   signed: false,
  //   name: 'A3, portrait, UU=1',
  //   fileName: 'pdf_suite_06.pdf',
  //   pageSizeCm: '29.70 x 42.00',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-07',
  //   signed: false,
  //   name: 'A5, portrait, UU=1',
  //   fileName: 'pdf_suite_07.pdf',
  //   pageSizeCm: '14.80 x 21.00',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-08',
  //   signed: false,
  //   name: 'Tabloid, landscape, UU=1',
  //   fileName: 'pdf_suite_08.pdf',
  //   pageSizeCm: '43.18 x 27.94',
  //   orientation: 'landscape',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-09',
  //   signed: false,
  //   name: 'A4, portrait, UU=0.5',
  //   fileName: 'pdf_suite_09.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 0.5,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-10',
  //   signed: false,
  //   name: 'A4, portrait, UU=2',
  //   fileName: 'pdf_suite_10.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 2.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-11',
  //   signed: false,
  //   name: 'Square 20x20 cm, UU=1',
  //   fileName: 'pdf_suite_11.pdf',
  //   pageSizeCm: '20.00 x 20.00',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [{ left: 5, top: 7, width: 8, height: 4, page: 1 }],
  // },
  // {
  //   key: 'suite-12',
  //   signed: false,
  //   name: 'A4 portrait, multiple signatures (UU=1)',
  //   fileName: 'pdf_suite_12.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 3,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 12,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 3,
  //       top: 10,
  //       width: 8,
  //       height: 4,
  //       page: 1,
  //     },
  //     {
  //       left: 5,
  //       top: 7,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //     {
  //       left: 10,
  //       top: 15,
  //       width: 5,
  //       height: 3,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-13',
  //   signed: false,
  //   name: 'A4 landscape, multiple signatures (UU=1)',
  //   fileName: 'pdf_suite_13.pdf',
  //   pageSizeCm: '29.70 x 21.00',
  //   orientation: 'landscape',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 3,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 18,
  //       top: 4,
  //       width: 8,
  //       height: 4,
  //       page: 1,
  //     },
  //     {
  //       left: 5,
  //       top: 7,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //     {
  //       left: 15,
  //       top: 12,
  //       width: 6,
  //       height: 3,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-14',
  //   signed: false,
  //   name: 'A2 portrait, large format (UU=1)',
  //   fileName: 'pdf_suite_14.pdf',
  //   pageSizeCm: '42.00 x 59.40',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 5,
  //       top: 8,
  //       width: 12,
  //       height: 6,
  //       page: 1,
  //     },
  //     {
  //       left: 15,
  //       top: 20,
  //       width: 12,
  //       height: 6,
  //       page: 1,
  //     },
  //     {
  //       left: 20,
  //       top: 25,
  //       width: 12,
  //       height: 6,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-15',
  //   signed: false,
  //   name: 'Postcard 10x15 cm, small format (UU=1)',
  //   fileName: 'pdf_suite_15.pdf',
  //   pageSizeCm: '10.00 x 15.00',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 1,
  //       top: 1,
  //       width: 4,
  //       height: 2,
  //       page: 1,
  //     },
  //     {
  //       left: 4.5,
  //       top: 6,
  //       width: 4.0,
  //       height: 2,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-16',
  //   signed: false,
  //   name: 'Custom 22x28 cm with background bands (UU=1)',
  //   fileName: 'pdf_suite_16.pdf',
  //   pageSizeCm: '22.00 x 28.00',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 2,
  //       top: 2,
  //       width: 8,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 10,
  //       top: 14,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-17',
  //   signed: false,
  //   name: 'A4 portrait (UU=1.5)',
  //   fileName: 'pdf_suite_17.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.5,
  //   signaturePlacement: [
  //     {
  //       left: 3,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 5,
  //       top: 7,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-18',
  //   signed: false,
  //   name: 'A4 portrait (UU=0.66)',
  //   fileName: 'pdf_suite_18.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 0.66,
  //   signaturePlacement: [
  //     {
  //       left: 3,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 12,
  //       top: 15,
  //       width: 6,
  //       height: 3,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-19',
  //   signed: false,
  //   name: 'A4 portrait with colored regions (UU=1)',
  //   fileName: 'pdf_suite_19.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 2,
  //       top: 2,
  //       width: 7,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 11,
  //       top: 10,
  //       width: 7,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 4,
  //       top: 18,
  //       width: 10,
  //       height: 4,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-20',
  //   signed: false,
  //   name: 'A4 portrait STRESS (many signatures) (UU=1)',
  //   fileName: 'pdf_suite_20.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 1.0,
  //       top: 2.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 5.8,
  //       top: 2.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 10.6,
  //       top: 2.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 15.399999999999999,
  //       top: 2.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 1.0,
  //       top: 5.5,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 5.8,
  //       top: 5.5,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 10.6,
  //       top: 5.5,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 15.399999999999999,
  //       top: 5.5,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 1.0,
  //       top: 9.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 5.8,
  //       top: 9.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 10.6,
  //       top: 9.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 15.399999999999999,
  //       top: 9.0,
  //       width: 4.2,
  //       height: 2.5,
  //       page: 1,
  //     },
  //     {
  //       left: 3,
  //       top: 5,
  //       width: 6,
  //       height: 3,
  //       page: 2,
  //     },
  //     {
  //       left: 11,
  //       top: 16,
  //       width: 6,
  //       height: 3,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-21',
  //   signed: false,
  //   name: 'Mixed page formats (A4 P, A4 L, Letter P, 20x20) (UU=1)',
  //   fileName: 'pdf_suite_21.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 5,
  //       top: 6,
  //       width: 8,
  //       height: 4,
  //       page: 1,
  //     },
  //     {
  //       left: 10,
  //       top: 5,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //     {
  //       left: 5,
  //       top: 6,
  //       width: 8,
  //       height: 4,
  //       page: 3,
  //     },
  //     {
  //       left: 4,
  //       top: 4,
  //       width: 12,
  //       height: 5,
  //       page: 4,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-22',
  //   signed: false,
  //   name: 'A4 portrait (no rotation) (UU=1)',
  //   fileName: 'pdf_suite_22.pdf',
  //   pageSizeCm: '21.00 x 29.70',
  //   orientation: 'portrait',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 3,
  //       top: 3,
  //       width: 6,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 5,
  //       top: 7,
  //       width: 8,
  //       height: 4,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-23',
  //   signed: false,
  //   name: 'Square 20x20 (UU=1.5)',
  //   fileName: 'pdf_suite_23.pdf',
  //   pageSizeCm: '20.00 x 20.00',
  //   orientation: 'portrait',
  //   userUnit: 1.5,
  //   signaturePlacement: [
  //     {
  //       left: 2,
  //       top: 2,
  //       width: 8,
  //       height: 3,
  //       page: 1,
  //     },
  //     {
  //       left: 10,
  //       top: 10,
  //       width: 8,
  //       height: 3,
  //       page: 2,
  //     },
  //   ],
  // },
  // {
  //   key: 'suite-24',
  //   signed: false,
  //   name: 'Tabloid landscape with backgrounds (UU=1)',
  //   fileName: 'pdf_suite_24.pdf',
  //   pageSizeCm: '43.18 x 27.94',
  //   orientation: 'landscape',
  //   userUnit: 1.0,
  //   signaturePlacement: [
  //     {
  //       left: 5,
  //       top: 5,
  //       width: 12,
  //       height: 5,
  //       page: 1,
  //     },
  //     {
  //       left: 25,
  //       top: 10,
  //       width: 12,
  //       height: 5,
  //       page: 2,
  //     },
  //   ],
  // },
  {
    key: 'suite-25',
    signed: true,
    name: 'Legal portrait (UU=0.66)',
    fileName: 'pdf_suite_25.pdf',
    pageSizeCm: '21.59 x 35.56',
    orientation: 'portrait',
    userUnit: 0.66,
    signaturePlacement: [
      {
        left: 4,
        top: 8,
        width: 8,
        height: 4,
        page: 1,
      },
      {
        left: 4,
        top: 20,
        width: 8,
        height: 4,
        page: 2,
      },
    ],
  },
]
